/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basiccalculator;

/**
 *
 * @author admin
 */
public class CalculatorGUI extends javax.swing.JPanel {

    /**
     * Creates new form CalculatorGUI
     */
    public CalculatorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton14 = new javax.swing.JButton();
        numberOneButton = new javax.swing.JButton();
        numberTwoButton = new javax.swing.JButton();
        numberThreeButton = new javax.swing.JButton();
        numberFourButton = new javax.swing.JButton();
        numberFiveButton = new javax.swing.JButton();
        numberSixButton = new javax.swing.JButton();
        numberSevenButton = new javax.swing.JButton();
        numberEightButton = new javax.swing.JButton();
        numberNineButton = new javax.swing.JButton();
        numberZeroButton = new javax.swing.JButton();
        additionButton = new javax.swing.JButton();
        substractionButton = new javax.swing.JButton();
        multiplicationButton = new javax.swing.JButton();
        divisionButton = new javax.swing.JButton();
        exponentialButton = new javax.swing.JButton();
        decimalButton = new javax.swing.JButton();
        negativeSymbolButton = new javax.swing.JButton();
        enterButton = new javax.swing.JButton();
        displayTextField = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        answerLabel = new javax.swing.JLabel();

        jButton14.setText("jButton14");

        numberOneButton.setFont(numberOneButton.getFont().deriveFont(numberOneButton.getFont().getStyle() | java.awt.Font.BOLD, numberOneButton.getFont().getSize()+10));
        numberOneButton.setText("1");
        numberOneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOneButtonActionPerformed(evt);
            }
        });

        numberTwoButton.setFont(numberTwoButton.getFont().deriveFont(numberTwoButton.getFont().getStyle() | java.awt.Font.BOLD, numberTwoButton.getFont().getSize()+10));
        numberTwoButton.setText("2");
        numberTwoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTwoButtonActionPerformed(evt);
            }
        });

        numberThreeButton.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        numberThreeButton.setText("3");
        numberThreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberThreeButtonActionPerformed(evt);
            }
        });

        numberFourButton.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        numberFourButton.setText("4");
        numberFourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberFourButtonActionPerformed(evt);
            }
        });

        numberFiveButton.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        numberFiveButton.setText("5");
        numberFiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberFiveButtonActionPerformed(evt);
            }
        });

        numberSixButton.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        numberSixButton.setText("6");
        numberSixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberSixButtonActionPerformed(evt);
            }
        });

        numberSevenButton.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        numberSevenButton.setText("7");
        numberSevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberSevenButtonActionPerformed(evt);
            }
        });

        numberEightButton.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        numberEightButton.setText("8");
        numberEightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberEightButtonActionPerformed(evt);
            }
        });

        numberNineButton.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        numberNineButton.setText("9");
        numberNineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberNineButtonActionPerformed(evt);
            }
        });

        numberZeroButton.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        numberZeroButton.setText("0");
        numberZeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberZeroButtonActionPerformed(evt);
            }
        });

        additionButton.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        additionButton.setText("+");
        additionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionButtonActionPerformed(evt);
            }
        });

        substractionButton.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        substractionButton.setText("-");
        substractionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                substractionButtonActionPerformed(evt);
            }
        });

        multiplicationButton.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        multiplicationButton.setText("*");
        multiplicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicationButtonActionPerformed(evt);
            }
        });

        divisionButton.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        divisionButton.setText("/");
        divisionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionButtonActionPerformed(evt);
            }
        });

        exponentialButton.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        exponentialButton.setText("^");
        exponentialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exponentialButtonActionPerformed(evt);
            }
        });

        decimalButton.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        decimalButton.setText(".");
        decimalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalButtonActionPerformed(evt);
            }
        });

        negativeSymbolButton.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        negativeSymbolButton.setText("(-)");
        negativeSymbolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negativeSymbolButtonActionPerformed(evt);
            }
        });

        enterButton.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        enterButton.setText("Enter");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        displayTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        clearButton.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        answerLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        answerLabel.setText("ANS: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(displayTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numberFiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numberSixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numberSevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numberEightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numberNineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numberZeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(decimalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(negativeSymbolButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numberOneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numberTwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numberThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numberFourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(substractionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exponentialButton, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(divisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(additionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(multiplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(enterButton, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(answerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberTwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberFourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numberFiveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(numberSixButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numberEightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numberSevenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numberNineButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(numberZeroButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(decimalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(negativeSymbolButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(substractionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(divisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(additionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(enterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(exponentialButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(multiplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    String textDisplayed = "";
    double prevNum = 0.0;
    char operator;
    
    private void numberOneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOneButtonActionPerformed
        textDisplayed += "1";
        displayTextField.setText(textDisplayed);
    }//GEN-LAST:event_numberOneButtonActionPerformed

    private void numberTwoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTwoButtonActionPerformed
        textDisplayed += "2";
        displayTextField.setText(textDisplayed);
    }//GEN-LAST:event_numberTwoButtonActionPerformed

    private void numberThreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberThreeButtonActionPerformed
        textDisplayed += "3";
        displayTextField.setText(textDisplayed);
    }//GEN-LAST:event_numberThreeButtonActionPerformed

    private void numberFourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberFourButtonActionPerformed
        textDisplayed += "4";
        displayTextField.setText(textDisplayed);
    }//GEN-LAST:event_numberFourButtonActionPerformed

    private void numberFiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberFiveButtonActionPerformed
        textDisplayed += "5";
        displayTextField.setText(textDisplayed);
    }//GEN-LAST:event_numberFiveButtonActionPerformed

    private void numberSixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberSixButtonActionPerformed
        textDisplayed += "6";
        displayTextField.setText(textDisplayed);
    }//GEN-LAST:event_numberSixButtonActionPerformed

    private void numberSevenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberSevenButtonActionPerformed
        textDisplayed += "7";
        displayTextField.setText(textDisplayed);
    }//GEN-LAST:event_numberSevenButtonActionPerformed

    private void numberEightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberEightButtonActionPerformed
        textDisplayed += "8";
        displayTextField.setText(textDisplayed);
    }//GEN-LAST:event_numberEightButtonActionPerformed

    private void numberNineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberNineButtonActionPerformed
        textDisplayed += "9";
        displayTextField.setText(textDisplayed);
    }//GEN-LAST:event_numberNineButtonActionPerformed

    private void numberZeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberZeroButtonActionPerformed
        textDisplayed += "0";
        displayTextField.setText(textDisplayed);
    }//GEN-LAST:event_numberZeroButtonActionPerformed

    private void decimalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalButtonActionPerformed
        textDisplayed += ".";
        displayTextField.setText(textDisplayed);
    }//GEN-LAST:event_decimalButtonActionPerformed

    private void negativeSymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negativeSymbolButtonActionPerformed
        textDisplayed = "-";
        displayTextField.setText(textDisplayed);
    }//GEN-LAST:event_negativeSymbolButtonActionPerformed

    private void substractionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_substractionButtonActionPerformed
        operator = '-';
        determineStateAndUpdate();
    }//GEN-LAST:event_substractionButtonActionPerformed

    private void divisionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionButtonActionPerformed
        operator = '/';
        determineStateAndUpdate();
    }//GEN-LAST:event_divisionButtonActionPerformed

    private void additionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionButtonActionPerformed
        operator = '+';
        determineStateAndUpdate();
    }//GEN-LAST:event_additionButtonActionPerformed

    private void multiplicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicationButtonActionPerformed
        operator = '*';
        determineStateAndUpdate();
    }//GEN-LAST:event_multiplicationButtonActionPerformed

    private void exponentialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exponentialButtonActionPerformed
        operator = '^';
        determineStateAndUpdate();
    }//GEN-LAST:event_exponentialButtonActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        prevNum = Calculator.performOperation(operator, prevNum, Double.parseDouble(textDisplayed));
        textDisplayed = "";
        displayTextField.setText(String.valueOf(prevNum));
        answerLabel.setText(String.valueOf(prevNum));
    }//GEN-LAST:event_enterButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clear();
    }//GEN-LAST:event_clearButtonActionPerformed
    
    private void determineStateAndUpdate(){
       if(prevNum != 0.0){
            performOperationAndUpdate();
        }
        else{
            updateWithoutPerforming();
        } 
    }
    
    private void clear(){
        textDisplayed = "";
        prevNum = 0.0;
        displayTextField.setText(textDisplayed);
    }
    
    private void performOperationAndUpdate(){
        if(textDisplayed.equals(""))
            textDisplayed = "2";
        prevNum  = Calculator.performOperation(operator, prevNum, Double.parseDouble(textDisplayed));
        answerLabel.setText(String.valueOf(prevNum));
        displayTextField.setText(String.valueOf(prevNum));
        textDisplayed = "";
    }
    
    private void updateWithoutPerforming(){
        prevNum = Double.parseDouble(textDisplayed);
        textDisplayed = "";
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton additionButton;
    private javax.swing.JLabel answerLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton decimalButton;
    private javax.swing.JTextField displayTextField;
    private javax.swing.JButton divisionButton;
    private javax.swing.JButton enterButton;
    private javax.swing.JButton exponentialButton;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton multiplicationButton;
    private javax.swing.JButton negativeSymbolButton;
    private javax.swing.JButton numberEightButton;
    private javax.swing.JButton numberFiveButton;
    private javax.swing.JButton numberFourButton;
    private javax.swing.JButton numberNineButton;
    private javax.swing.JButton numberOneButton;
    private javax.swing.JButton numberSevenButton;
    private javax.swing.JButton numberSixButton;
    private javax.swing.JButton numberThreeButton;
    private javax.swing.JButton numberTwoButton;
    private javax.swing.JButton numberZeroButton;
    private javax.swing.JButton substractionButton;
    // End of variables declaration//GEN-END:variables
}
